import { Bounds } from '../../geometry/Bounds';
import { LatLng } from '../../geo/LatLng';
import { LatLngBounds } from '../../geo/LatLngBounds';
import { Path } from './Path';
import { Point } from '../../geometry/Point';
export declare class Polyline extends Path {
  _latlngs: any[];
  _bounds: LatLngBounds;
  _rings: Point[][];
  _rawPxBounds?: Bounds;
  initialize(latlngs: any[], options?: any): void;
  getLatLngs(): any[];
  setLatLngs(latlngs: any[]): this;
  isEmpty(): boolean;
  closestLayerPoint(p: Point): (Point & { distance?: number }) | null;
  getCenter(): LatLng;
  getBounds(): LatLngBounds;
  addLatLng(latlng: any, latlngs?: any[]): this;
  _setLatLngs(latlngs: any[]): void;
  _defaultShape(): any[];
  _convertLatLngs(latlngs: any[]): any[];
  _project(): void;
  _updateBounds(): void;
  _projectLatlngs(latlngs: any[], result: Point[][], projectedBounds: Bounds): void;
  _clipPoints(): void;
  _simplifyPoints(): void;
  _update(): void;
  _updatePath(): void;
  _containsPoint(p: Point, closed?: boolean): boolean;
}
