#!/usr/bin/env bun
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { generateMobileAssociations } from './scripts/generate-mobile-associations'

const requestedSource = process.env.STX_SOURCE_ROOT?.trim()
const sourceRoot = requestedSource || ''
const { buildApp } = sourceRoot
  ? await import(pathToFileURL(join(sourceRoot, 'packages/stx/src/build.ts')).href)
  : await import('@stacksjs/stx')

// eslint-disable-next-line ts/no-top-level-await
await generateMobileAssociations()
// Mobile packaging must never reuse HTML generated by a different STX runtime;
// the native bundle is immutable once it is copied into the platform project.
// eslint-disable-next-line ts/no-top-level-await
await buildApp(process.env.MOBILE_E2E ? { ssg: { cache: false } } : {})
