// Generated by bun-plugin-auto-imports

// This file injects auto-imported functions into the global scope
// Import this file early in your application startup

import * as autoImports from './index'

// Inject into globalThis for runtime access
Object.assign(globalThis, autoImports)

// TypeScript declarations
declare global {
  const computeTerritoryRankAssignments: typeof autoImports.computeTerritoryRankAssignments
  const increment: typeof autoImports.increment
  const count: typeof autoImports.count
  const shapeChallenge: typeof autoImports.shapeChallenge
  const renderActivitySharePng: typeof autoImports.renderActivitySharePng
  const downloadActivityShareImage: typeof autoImports.downloadActivityShareImage
  const shareActivityImage: typeof autoImports.shareActivityImage
  const activityShareOptions: typeof autoImports.activityShareOptions
  const activityShareSvg: typeof autoImports.activityShareSvg
  const activitySharePreview: typeof autoImports.activitySharePreview
  const readPageParams: typeof autoImports.readPageParams
  const paginate: typeof autoImports.paginate
  const longestDayStreak: typeof autoImports.longestDayStreak
  const hasSubSevenMile: typeof autoImports.hasSubSevenMile
  const computeAchievementProgress: typeof autoImports.computeAchievementProgress
  const achievementMetricValues: typeof autoImports.achievementMetricValues
  const extractMentionQuery: typeof autoImports.extractMentionQuery
  const mentionCandidates: typeof autoImports.mentionCandidates
  const applyMention: typeof autoImports.applyMention
  const parseMentions: typeof autoImports.parseMentions
  const routeIsRankable: typeof autoImports.routeIsRankable
  const elapsedSeconds: typeof autoImports.elapsedSeconds
  const formatElapsed: typeof autoImports.formatElapsed
  const recordPace: typeof autoImports.recordPace
  const recordBucketKey: typeof autoImports.recordBucketKey
  const rankBucket: typeof autoImports.rankBucket
  const buildRecordBoards: typeof autoImports.buildRecordBoards
  const outrightRecord: typeof autoImports.outrightRecord
  const beatsMoreRestrictiveStyles: typeof autoImports.beatsMoreRestrictiveStyles
  const isHeadlineRecord: typeof autoImports.isHeadlineRecord
  const evidenceIsSufficient: typeof autoImports.evidenceIsSufficient
  const normalizeEvidenceUrl: typeof autoImports.normalizeEvidenceUrl
  const normalizeTrackerUrl: typeof autoImports.normalizeTrackerUrl
  const RECORD_STYLES: typeof autoImports.RECORD_STYLES
  const RECORD_CATEGORIES: typeof autoImports.RECORD_CATEGORIES
  const RECORD_DIRECTIONS: typeof autoImports.RECORD_DIRECTIONS
  const RECORD_STATUSES: typeof autoImports.RECORD_STATUSES
  const RANKED_STATUSES: typeof autoImports.RANKED_STATUSES
  const STYLE_LABELS: typeof autoImports.STYLE_LABELS
  const CATEGORY_LABELS: typeof autoImports.CATEGORY_LABELS
  const DIRECTION_LABELS: typeof autoImports.DIRECTION_LABELS
  const STATUS_LABELS: typeof autoImports.STATUS_LABELS
  const MIN_RECORD_DISTANCE_MI: typeof autoImports.MIN_RECORD_DISTANCE_MI
  const MIN_RECORD_ELEVATION_FT: typeof autoImports.MIN_RECORD_ELEVATION_FT
  const totalElevationGainFt: typeof autoImports.totalElevationGainFt
  const computeSplitsFromSamples: typeof autoImports.computeSplitsFromSamples
  const ELEVATION_NOISE_FLOOR_FT: typeof autoImports.ELEVATION_NOISE_FLOOR_FT
  const METERS_TO_FEET: typeof autoImports.METERS_TO_FEET
  const blockedUserIdsFor: typeof autoImports.blockedUserIdsFor
  const canViewActivity: typeof autoImports.canViewActivity
  const maskRouteEndpoints: typeof autoImports.maskRouteEndpoints
  const isDark: typeof autoImports.isDark
  const toggleDark: typeof autoImports.toggleDark
  const preferredDark: typeof autoImports.preferredDark
  const qrSvg: typeof autoImports.qrSvg
  const qrSvgMarkup: typeof autoImports.qrSvgMarkup
  const qrBrandedMarkup: typeof autoImports.qrBrandedMarkup
  const positiveInt: typeof autoImports.positiveInt
  const boundedNumber: typeof autoImports.boundedNumber
  const boundedString: typeof autoImports.boundedString
  const durationString: typeof autoImports.durationString
  const XP_REWARDS: typeof autoImports.XP_REWARDS
  const yardStartsAt: typeof autoImports.yardStartsAt
  const currentYard: typeof autoImports.currentYard
  const msToNextStart: typeof autoImports.msToNextStart
  const msIntoCurrentYard: typeof autoImports.msIntoCurrentYard
  const yardsRequiredToBeIn: typeof autoImports.yardsRequiredToBeIn
  const isStillIn: typeof autoImports.isStillIn
  const standings: typeof autoImports.standings
  const resolveOutcome: typeof autoImports.resolveOutcome
  const formatClock: typeof autoImports.formatClock
  const STANDARD_YARD_MILES: typeof autoImports.STANDARD_YARD_MILES
  const STANDARD_YARD_MINUTES: typeof autoImports.STANDARD_YARD_MINUTES
  const parseGpx: typeof autoImports.parseGpx
  const parseJsonCoordinates: typeof autoImports.parseJsonCoordinates
  const parseGpsData: typeof autoImports.parseGpsData
  const generateSampleLoopGpx: typeof autoImports.generateSampleLoopGpx
  const generateSampleLoopJson: typeof autoImports.generateSampleLoopJson
  const validateGpsDataForClaim: typeof autoImports.validateGpsDataForClaim
  const validateTrackRealism: typeof autoImports.validateTrackRealism
  const parseActivityFile: typeof autoImports.parseActivityFile
  const parseGpxActivity: typeof autoImports.parseGpxActivity
  const parseTcxActivity: typeof autoImports.parseTcxActivity
  const parseFitActivity: typeof autoImports.parseFitActivity
  const escapeXml: typeof autoImports.escapeXml
  const importedTrackGeoJson: typeof autoImports.importedTrackGeoJson
  const trackToGpx: typeof autoImports.trackToGpx
  const downloadGpxFile: typeof autoImports.downloadGpxFile
  const MAX_ACTIVITY_FILE_BYTES: typeof autoImports.MAX_ACTIVITY_FILE_BYTES
  const MAX_ACTIVITY_TRACK_POINTS: typeof autoImports.MAX_ACTIVITY_TRACK_POINTS
  const classifyBattleOutcome: typeof autoImports.classifyBattleOutcome
  const parseDurationToSeconds: typeof autoImports.parseDurationToSeconds
  const paceString: typeof autoImports.paceString
  const territoryFreshnessMs: typeof autoImports.territoryFreshnessMs
  const computeTerritoryDecay: typeof autoImports.computeTerritoryDecay
  const DECAY_STALE_DAYS: typeof autoImports.DECAY_STALE_DAYS
  const DECAY_EXPIRE_DAYS: typeof autoImports.DECAY_EXPIRE_DAYS
  const isLiveGpsSource: typeof autoImports.isLiveGpsSource
  const parseTrackSamples: typeof autoImports.parseTrackSamples
  const evaluateTrackIntegrity: typeof autoImports.evaluateTrackIntegrity
  const durationLabel: typeof autoImports.durationLabel
  const computeConquestRecord: typeof autoImports.computeConquestRecord
  const computeCounterFixes: typeof autoImports.computeCounterFixes
  const computeTrainingStats: typeof autoImports.computeTrainingStats
  const haversineDistance: typeof autoImports.haversineDistance
  const isClosedLoop: typeof autoImports.isClosedLoop
  const calculatePolygonArea: typeof autoImports.calculatePolygonArea
  const calculatePerimeter: typeof autoImports.calculatePerimeter
  const simplifyTrack: typeof autoImports.simplifyTrack
  const pointInPolygon: typeof autoImports.pointInPolygon
  const lineIntersectsPolygon: typeof autoImports.lineIntersectsPolygon
  const routeIntersectsPolygon: typeof autoImports.routeIntersectsPolygon
  const getBoundingBox: typeof autoImports.getBoundingBox
  const parseBoundingBox: typeof autoImports.parseBoundingBox
  const boundingBoxesOverlap: typeof autoImports.boundingBoxesOverlap
  const polygonsOverlap: typeof autoImports.polygonsOverlap
  const getCentroid: typeof autoImports.getCentroid
  const coordinatesToGeoJson: typeof autoImports.coordinatesToGeoJson
  const geoJsonToCoordinates: typeof autoImports.geoJsonToCoordinates
  const findLinePolygonIntersections: typeof autoImports.findLinePolygonIntersections
  const splitPolygonByRoute: typeof autoImports.splitPolygonByRoute
  const generateLoopCoordinates: typeof autoImports.generateLoopCoordinates
}

export {}
