// Generated by bun-plugin-auto-imports

// This file injects auto-imported functions into the global scope
// Import this file early in your application startup

import * as autoImports from './index'

// Inject into globalThis for runtime access
Object.assign(globalThis, autoImports)

// TypeScript declarations
declare global {
  const computeTerritoryRankAssignments: typeof autoImports.computeTerritoryRankAssignments
  const increment: typeof autoImports.increment
  const count: typeof autoImports.count
  const isDark: typeof autoImports.isDark
  const toggleDark: typeof autoImports.toggleDark
  const preferredDark: typeof autoImports.preferredDark
  const parseGpx: typeof autoImports.parseGpx
  const parseJsonCoordinates: typeof autoImports.parseJsonCoordinates
  const parseGpsData: typeof autoImports.parseGpsData
  const generateSampleLoopGpx: typeof autoImports.generateSampleLoopGpx
  const generateSampleLoopJson: typeof autoImports.generateSampleLoopJson
  const validateGpsDataForClaim: typeof autoImports.validateGpsDataForClaim
  const validateTrackRealism: typeof autoImports.validateTrackRealism
  const territoryFreshnessMs: typeof autoImports.territoryFreshnessMs
  const computeTerritoryDecay: typeof autoImports.computeTerritoryDecay
  const DECAY_STALE_DAYS: typeof autoImports.DECAY_STALE_DAYS
  const DECAY_EXPIRE_DAYS: typeof autoImports.DECAY_EXPIRE_DAYS
  const haversineDistance: typeof autoImports.haversineDistance
  const isClosedLoop: typeof autoImports.isClosedLoop
  const calculatePolygonArea: typeof autoImports.calculatePolygonArea
  const calculatePerimeter: typeof autoImports.calculatePerimeter
  const simplifyTrack: typeof autoImports.simplifyTrack
  const pointInPolygon: typeof autoImports.pointInPolygon
  const lineIntersectsPolygon: typeof autoImports.lineIntersectsPolygon
  const routeIntersectsPolygon: typeof autoImports.routeIntersectsPolygon
  const getBoundingBox: typeof autoImports.getBoundingBox
  const parseBoundingBox: typeof autoImports.parseBoundingBox
  const boundingBoxesOverlap: typeof autoImports.boundingBoxesOverlap
  const polygonsOverlap: typeof autoImports.polygonsOverlap
  const getCentroid: typeof autoImports.getCentroid
  const coordinatesToGeoJson: typeof autoImports.coordinatesToGeoJson
  const geoJsonToCoordinates: typeof autoImports.geoJsonToCoordinates
  const findLinePolygonIntersections: typeof autoImports.findLinePolygonIntersections
  const splitPolygonByRoute: typeof autoImports.splitPolygonByRoute
  const generateLoopCoordinates: typeof autoImports.generateLoopCoordinates
  const normalizeElement: typeof autoImports.normalizeElement
  const getTrailCentroid: typeof autoImports.getTrailCentroid
  const generateTiles: typeof autoImports.generateTiles
  const getRegion: typeof autoImports.getRegion
  const regions: typeof autoImports.regions
  const fetchTile: typeof autoImports.fetchTile
  const deduplicateTrails: typeof autoImports.deduplicateTrails
}

export {}
