// Generated by ts-cloud for the management dashboard — do not edit.
//
// This is the project's resolved cloud config, inlined so it needs no
// imports on the box. Credentials are deliberately absent.
export default {
  "project": {
    "name": "WildLoop",
    "slug": "wildloop",
    "region": "us-east-1"
  },
  "cloud": {
    "provider": "hetzner",
    "attachTo": "stacks"
  },
  "mode": "server",
  "environments": {
    "production": {
      "type": "production",
      "domain": "wildloop.org"
    }
  },
  "sites": {
    "main": {
      "root": ".",
      "path": "/",
      "domain": "wildloop.org",
      "start": "./buddy serve",
      "port": 3049
    },
    "www": {
      "domain": "www.wildloop.org",
      "redirect": {
        "to": "https://wildloop.org",
        "status": 301
      }
    }
  },
  "infrastructure": {
    "dns": {
      "provider": "porkbun",
      "domain": "wildloop.org"
    }
  }
}
