/* eslint-disable */
// AUTO-GENERATED by `buddy generate:db-types` — do not edit.
// Regenerate after adding/removing a model or changing its attributes.
// See stacksjs/stacks#1923.

declare module '@stacksjs/database' {
  interface DatabaseSchema {
    achievements: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      icon: unknown
      category: unknown
      metric: unknown
      target_value: unknown
      target_unit: unknown
      points: unknown
      badge_color: unknown
    }
    activities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      trail_id: number
      activity_type: unknown
      distance: unknown
      duration: unknown
      moving_time: unknown | null
      pace: unknown
      elevation: unknown
      kudos_count: unknown
      notes: unknown
      gpx_data: unknown
      splits: unknown | null
      visibility: unknown
      upload_id: unknown | null
      recording_source: unknown
      game_mode: unknown
      capture_eligible: unknown
      integrity_status: unknown
      integrity_reason: unknown | null
      completed_at: unknown
    }
    activity_comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: unknown
      activity_id: unknown
      body: unknown
    }
    authors: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      email: unknown
      bio: unknown
      avatar: unknown
      user_id: number
    }
    board_columns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: unknown
      position: unknown
      card_limit: unknown
      color: unknown
    }
    boards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      icon: unknown
      color: unknown
      position: unknown
      archived: unknown
    }
    campaign_sends: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      campaign_id: number
      subscriber_id: number
      email_list_id: number
      status: unknown
      provider_message_id: unknown
      error: unknown
      sent_at: unknown
      opened_at: unknown
      clicked_at: unknown
    }
    campaigns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      type: unknown
      status: unknown
      subject: unknown
      template: unknown
      text: unknown
      from_name: unknown
      from_address: unknown
      email_list_id: number
      scheduled_at: unknown
      sent_at: unknown
      audience_size: unknown
      sent_count: unknown
      open_rate: unknown
      click_rate: unknown
      conversion_rate: unknown
      budget: unknown
      spent: unknown
      start_date: unknown
      end_date: unknown
    }
    card_comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      card_id: number
      user_id: number
      body: unknown
    }
    cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      column_id: unknown
      board_id: number
      title: unknown
      description: unknown
      position: unknown
      created_by_user_id: unknown
      due_date: unknown
      archived: unknown
      board_column_id: number
      user_id: number
    }
    cart_items: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      quantity: unknown
      unit_price: unknown
      total_price: unknown
      tax_rate: unknown
      tax_amount: unknown
      discount_percentage: unknown
      discount_amount: unknown
      product_name: unknown
      product_sku: unknown
      product_image: unknown
      notes: unknown
      cart_id: number
    }
    carts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: unknown
      total_items: unknown
      subtotal: unknown
      tax_amount: unknown
      discount_amount: unknown
      total: unknown
      expires_at: unknown
      currency: unknown
      notes: unknown
      applied_coupon_id: unknown
      customer_id: number
      coupon_id: number
    }
    categories: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      slug: unknown
      image_url: unknown
      is_active: unknown
      parent_category_id: unknown
      display_order: unknown
    }
    challenges: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      challenger_id: unknown
      challenged_id: unknown
      territory_id: unknown
      area_at_stake: unknown
      status: unknown
      winner_id: unknown | null
      deadline: unknown
    }
    club_members: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      club_id: unknown
      user_id: unknown
      role: unknown
    }
    clubs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      creator_id: unknown
      name: unknown
      description: unknown | null
      location: unknown | null
      club_type: unknown
      is_private: unknown
    }
    comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      author_name: unknown
      author_email: unknown
      content: unknown
      body: unknown
      post_title: unknown
      status: unknown
      ip_address: unknown
      user_agent: unknown
      is_approved: unknown
      post_id: number
      user_id: number
    }
    content_reports: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      reporter_id: unknown
      subject_type: unknown
      subject_id: unknown
      reason: unknown
      details: unknown | null
      status: unknown
      resolved_by: unknown | null
      resolution_notes: unknown | null
    }
    coupons: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: unknown
      description: unknown
      status: unknown
      is_active: unknown
      discount_type: unknown
      discount_value: unknown
      min_order_amount: unknown
      max_discount_amount: unknown
      free_product_id: unknown
      usage_limit: unknown
      usage_count: unknown
      start_date: unknown
      end_date: unknown
      product_id: number
    }
    custom_routes: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      name: unknown
      route_data: unknown
      distance: unknown
      elevation: unknown
      closed_loop: unknown
    }
    customers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      email: unknown
      phone: unknown
      total_spent: unknown
      last_order: unknown
      status: unknown
      avatar: unknown
      user_id: number
    }
    delivery_routes: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      driver: unknown
      vehicle: unknown
      stops: unknown
      delivery_time: unknown
      total_distance: unknown
      last_active: unknown
    }
    deployments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      commit_hash: unknown
      commit_message: unknown
      branch: unknown
      status: unknown
      environment: unknown
      duration: unknown
      author: unknown
      url: unknown
      error_log: unknown
    }
    digital_deliveries: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      download_limit: unknown
      expiry_days: unknown
      requires_login: unknown
      automatic_delivery: unknown
      status: unknown
    }
    drivers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      phone: unknown
      vehicle_number: unknown
      license: unknown
      status: unknown
      user_id: number
    }
    email_list_subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email_list_id: number
      subscriber_id: number
      status: unknown
      source: unknown
      subscribed_at: unknown
      unsubscribed_at: unknown
    }
    email_lists: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      slug: unknown
      description: unknown
      subscriber_count: unknown
      active_count: unknown
      unsubscribed_count: unknown
      bounced_count: unknown
      status: unknown
      is_public: unknown
      double_opt_in: unknown
    }
    errors: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: unknown
      message: unknown
      stack: unknown
      status: unknown
      additional_info: unknown
    }
    failed_jobs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      connection: unknown
      queue: unknown
      payload: unknown
      exception: unknown
      failed_at: unknown
    }
    follows: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      follower_id: unknown
      following_id: unknown
    }
    gift_cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: unknown
      initial_balance: unknown
      current_balance: unknown
      currency: unknown
      status: unknown
      purchaser_id: unknown
      recipient_email: unknown
      recipient_name: unknown
      personal_message: unknown
      is_digital: unknown
      is_reloadable: unknown
      is_active: unknown
      expiry_date: unknown
      last_used_date: unknown
      template_id: unknown
      customer_id: number
    }
    jobs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      queue: unknown
      payload: unknown
      attempts: unknown
      available_at: unknown
      reserved_at: unknown
    }
    kudos: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      giver_id: unknown
      user_id: number
      activity_id: number
    }
    labels: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: unknown
      color: unknown
    }
    license_keys: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      key: unknown
      template: unknown
      expiry_date: unknown
      status: unknown
      customer_id: number
      product_id: number
      order_id: number
    }
    logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      timestamp: unknown
      type: unknown
      source: unknown
      message: unknown
      project: unknown
      stacktrace: unknown
      file: unknown
    }
    loyalty_points: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      wallet_id: unknown
      points: unknown
      source: unknown
      source_reference_id: unknown
      description: unknown
      expiry_date: unknown
      is_used: unknown
    }
    loyalty_rewards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      points_required: unknown
      reward_type: unknown
      discount_percentage: unknown
      free_product_id: unknown
      is_active: unknown
      expiry_days: unknown
      image_url: unknown
      product_id: number
    }
    manufacturers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      manufacturer: unknown
      description: unknown
      country: unknown
      featured: unknown
    }
    notifications: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: unknown
      channel: unknown
      recipient: unknown
      subject: unknown
      body: unknown
      status: unknown
      read_at: unknown
      sent_at: unknown
      metadata: unknown
      user_id: number
    }
    order_items: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      quantity: unknown
      price: unknown
      special_instructions: unknown
      order_id: number
      product_id: number
    }
    orders: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: unknown
      total_amount: unknown
      tax_amount: unknown
      discount_amount: unknown
      delivery_fee: unknown
      tip_amount: unknown
      order_type: unknown
      delivery_address: unknown
      special_instructions: unknown
      estimated_delivery_time: unknown
      applied_coupon_id: unknown
      customer_id: number
      coupon_id: number
    }
    pages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: unknown
      template: unknown
      views: unknown
      published_at: unknown
      conversions: unknown
      author_id: number
    }
    payment_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: unknown
      last_four: unknown
      brand: unknown
      exp_month: unknown
      exp_year: unknown
      is_default: unknown
      provider_id: unknown
      user_id: number
    }
    payment_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      key: unknown
      unit_price: unknown
      status: unknown
      image: unknown
      provider_id: unknown
    }
    payment_transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      amount: unknown
      type: unknown
      provider_id: unknown
      user_id: number
      payment_method_id: number
    }
    payments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: unknown
      method: unknown
      status: unknown
      currency: unknown
      reference_number: unknown
      card_last_four: unknown
      card_brand: unknown
      billing_email: unknown
      transaction_id: unknown
      payment_provider: unknown
      refund_amount: unknown
      notes: unknown
      order_id: number
      customer_id: number
    }
    posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: unknown
      poster: unknown
      content: unknown
      excerpt: unknown
      views: unknown
      published_at: unknown
      status: unknown
      is_featured: unknown
      author_id: number
    }
    print_devices: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      mac_address: unknown
      location: unknown
      terminal: unknown
      status: unknown
      last_ping: unknown
      print_count: unknown
    }
    product_units: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      abbreviation: unknown
      type: unknown
      description: unknown
      is_default: unknown
      product_id: number
    }
    product_variants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      variant: unknown
      type: unknown
      description: unknown
      options: unknown
      status: unknown
      product_id: number
    }
    products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      price: unknown
      image_url: unknown
      is_available: unknown
      inventory_count: unknown
      preparation_time: unknown
      allergens: unknown
      nutritional_info: unknown
      category_id: number
      manufacturer_id: number
    }
    receipts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      printer: unknown
      document: unknown
      timestamp: unknown
      status: unknown
      size: unknown
      pages: unknown
      duration: unknown
      metadata: unknown
      print_device_id: number
    }
    releases: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      version: unknown
      type: unknown
      status: unknown
      notes: unknown
      downloads: unknown
      author: unknown
    }
    requests: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      deleted_at: string | null
      method: unknown
      path: unknown
      status_code: unknown
      duration_ms: unknown
      ip_address: unknown
      memory_usage: unknown
      user_agent: unknown
      error_message: unknown
    }
    saved_trails: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      trail_id: number
      notes: unknown | null
      want_to_visit: unknown
      has_visited: unknown
    }
    shipping_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      base_rate: unknown
      free_shipping: unknown
      status: unknown
    }
    shipping_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      weight_from: unknown
      weight_to: unknown
      rate: unknown
      shipping_method_id: number
      shipping_zone_id: number
    }
    shipping_zones: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      countries: unknown
      regions: unknown
      postal_codes: unknown
      status: unknown
      shipping_method_id: number
    }
    social_posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      content: unknown
      platform: unknown
      status: unknown
      scheduled_at: unknown
      published_at: unknown
      likes: unknown
      shares: unknown
      comments: unknown
      reach: unknown
      image_url: unknown
      external_id: unknown
      user_id: number
    }
    subscriber_emails: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: unknown
      source: unknown
      subscriber_id: number
    }
    subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: unknown
      status: unknown
      source: unknown
      unsubscribed_at: unknown
      user_id: number
    }
    subscriptions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: unknown
      plan: unknown
      provider_id: unknown
      provider_status: unknown
      unit_price: unknown
      provider_type: unknown
      provider_price_id: unknown
      quantity: unknown
      trial_ends_at: unknown
      ends_at: unknown
      last_used_at: unknown
      user_id: number
    }
    tags: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      slug: unknown
      description: unknown
      post_count: unknown
      color: unknown
    }
    tax_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      rate: unknown
      type: unknown
      country: unknown
      region: unknown
      status: unknown
      is_default: unknown
    }
    teams: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      member_count: unknown
      status: unknown
    }
    territories: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      activity_id: number
      parent_territory_id: unknown | null
      name: unknown | null
      polygon_data: unknown
      bounding_box: unknown | null
      min_lat: unknown | null
      min_lng: unknown | null
      max_lat: unknown | null
      max_lng: unknown | null
      center_lat: unknown
      center_lng: unknown
      area_size: unknown
      perimeter: unknown | null
      status: unknown
      conquest_count: unknown
      claimed_at: unknown
      last_activity_at: unknown | null
    }
    territory_histories: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      territory_id: number
      user_id: number
      activity_id: number
      previous_owner_id: unknown | null
      event_type: unknown
      area_at_event: unknown | null
      previous_ownership_duration: unknown | null
      notes: unknown | null
      new_territory_id: unknown | null
    }
    territory_stats: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      total_territories_owned: unknown
      total_area_owned: unknown
      territories_claimed: unknown
      territories_conquered: unknown
      territories_lost: unknown
      territories_defended: unknown
      longest_ownership_days: unknown
      largest_territory_area: unknown
      weekly_rank: unknown | null
      all_time_rank: unknown | null
      xp: unknown
    }
    trail_ingest_shards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      shard_key: unknown
      source: unknown
      cursor: unknown
      status: unknown
      attempts: unknown
      features_seen: unknown
      trails_imported: unknown
      trails_updated: unknown
      last_error: unknown
      started_at: unknown
      completed_at: unknown
    }
    trail_reviews: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      trail_id: number
      rating: unknown
      title: unknown | null
      content: unknown
      visit_date: unknown | null
      conditions: unknown | null
      helpful_count: unknown
      photos: unknown | null
    }
    trails: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      location: unknown
      distance: unknown
      elevation: unknown
      difficulty: unknown
      rating: unknown
      review_count: unknown
      estimated_time: unknown
      image: unknown
      tags: unknown
      latitude: unknown
      longitude: unknown
      description: unknown
      geometry: unknown
      source: unknown
      source_id: unknown
      source_url: unknown
      synced_at: unknown
      country: unknown
      state: unknown
      state_name: unknown
      managed_by: unknown
      min_lat: unknown
      max_lat: unknown
      min_lng: unknown
      max_lng: unknown
      route_type: unknown
      surface: unknown
      elevation_high: unknown
      allowed_uses: unknown
      dogs_allowed: unknown
      wheelchair_accessible: unknown
      national_trail: unknown
    }
    transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: unknown
      status: unknown
      payment_method: unknown
      payment_details: unknown
      transaction_reference: unknown
      loyalty_points_earned: unknown
      loyalty_points_redeemed: unknown
      order_id: number
    }
    user_achievements: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      achievement_id: number
      progress: unknown
      completed_at: unknown | null
      is_complete: unknown
    }
    user_blocks: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      blocker_id: unknown
      blocked_id: unknown
    }
    user_notifications: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      recipient_id: unknown
      actor_id: unknown
      actor_name: unknown
      type: unknown
      body: unknown
      link: unknown
      read: unknown
    }
    user_privacy_settings: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      default_activity_visibility: unknown
      hide_start_end_meters: unknown
      home_lat: unknown | null
      home_lng: unknown | null
      home_radius_meters: unknown
      exclude_home_from_game: unknown
      show_precise_territories: unknown
    }
    user_stats: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      total_distance: unknown
      total_time: unknown
      total_elevation: unknown
      trails_completed: unknown
      current_streak: unknown
      longest_streak: unknown
      weekly_rank: unknown
      total_activities: unknown
      total_kudos_received: unknown
      total_kudos_given: unknown
      user_id: number
    }
    users: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      email: unknown
      password: unknown
    }
    waitlist_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      email: unknown
      phone: unknown
      quantity: unknown
      notification_preference: unknown
      source: unknown
      notes: unknown
      status: unknown
      notified_at: unknown
      purchased_at: unknown
      cancelled_at: unknown
      product_id: number
      customer_id: number
    }
    waitlist_restaurants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      email: unknown
      phone: unknown
      party_size: unknown
      check_in_time: unknown
      table_preference: unknown
      status: unknown
      quoted_wait_time: unknown
      actual_wait_time: unknown
      queue_position: unknown
      seated_at: unknown
      no_show_at: unknown
      cancelled_at: unknown
      customer_id: number
    }
    websockets: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: unknown
      socket: unknown
      details: unknown
      time: unknown
    }
  }
}

export {}
