// Generated by bun-plugin-auto-imports

// Global type declarations for auto-imported modules
// This file is auto-generated - do not edit manually

import type * as ___functions from '@/functions'

declare global {
  const increment: typeof ___functions.increment
  const count: typeof ___functions.count
  const isDark: typeof ___functions.isDark
  const toggleDark: typeof ___functions.toggleDark
  const preferredDark: typeof ___functions.preferredDark
  const parseGpx: typeof ___functions.parseGpx
  const parseJsonCoordinates: typeof ___functions.parseJsonCoordinates
  const parseGpsData: typeof ___functions.parseGpsData
  const generateSampleLoopGpx: typeof ___functions.generateSampleLoopGpx
  const generateSampleLoopJson: typeof ___functions.generateSampleLoopJson
  const validateGpsDataForClaim: typeof ___functions.validateGpsDataForClaim
  const haversineDistance: typeof ___functions.haversineDistance
  const isClosedLoop: typeof ___functions.isClosedLoop
  const calculatePolygonArea: typeof ___functions.calculatePolygonArea
  const calculatePerimeter: typeof ___functions.calculatePerimeter
  const simplifyTrack: typeof ___functions.simplifyTrack
  const pointInPolygon: typeof ___functions.pointInPolygon
  const lineIntersectsPolygon: typeof ___functions.lineIntersectsPolygon
  const routeIntersectsPolygon: typeof ___functions.routeIntersectsPolygon
  const getBoundingBox: typeof ___functions.getBoundingBox
  const parseBoundingBox: typeof ___functions.parseBoundingBox
  const boundingBoxesOverlap: typeof ___functions.boundingBoxesOverlap
  const getCentroid: typeof ___functions.getCentroid
  const coordinatesToGeoJson: typeof ___functions.coordinatesToGeoJson
  const geoJsonToCoordinates: typeof ___functions.geoJsonToCoordinates
  const findLinePolygonIntersections: typeof ___functions.findLinePolygonIntersections
  const splitPolygonByRoute: typeof ___functions.splitPolygonByRoute
  const generateLoopCoordinates: typeof ___functions.generateLoopCoordinates
  type Coordinate = ___functions.Coordinate
  type GeoJsonPolygon = ___functions.GeoJsonPolygon
}

export {}
