import { LatLng } from '../../geo/LatLng';
import { Layer } from '../Layer';
import { MarkerDrag } from './Marker.Drag';
import { Point } from '../../geometry/Point';
export declare class Marker extends Layer {
  _latlng: LatLng;
  _icon?: HTMLElement | null;
  _shadow?: HTMLElement | null;
  _zIndex?: number;
  _popup?: any;
  dragging?: MarkerDrag;
  initialize(latlng: any, options?: any): void;
  onAdd(map: any): void;
  onRemove(map: any): void;
  getEvents(): Record<string, any>;
  getLatLng(): LatLng;
  setLatLng(latlng: any): this;
  setZIndexOffset(offset: number): this;
  getIcon(): any;
  setIcon(icon: any): this;
  getElement(): HTMLElement | null | undefined;
  update(): this;
  _initIcon(): void;
  _removeIcon(): void;
  _removeShadow(): void;
  _setPos(pos: Point): void;
  _updateZIndex(offset: number): void;
  _animateZoom(opt: any): void;
  _initInteraction(): void;
  setOpacity(opacity: number): this;
  _updateOpacity(): void;
  _bringToFront(): void;
  _resetZIndex(): void;
  _panOnFocus(): void;
  _getPopupAnchor(): any;
  _getTooltipAnchor(): any;
}
