CREATE TABLE IF NOT EXISTS "trails" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT,
  "location" TEXT,
  "distance" REAL,
  "elevation" REAL,
  "difficulty" TEXT CHECK ("difficulty" IN ('easy', 'moderate', 'hard')),
  "rating" REAL,
  "review_count" INTEGER,
  "estimated_time" TEXT,
  "image" TEXT,
  "tags" TEXT,
  "latitude" REAL,
  "longitude" REAL,
  "description" TEXT,
  "geometry" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);