-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE UNIQUE INDEX IF NOT EXISTS "territory_stats_user_unique" ON "territory_stats" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "territory_stats_uuid_unique" ON "territory_stats" ("uuid");
