-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_user_notifications" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "recipient_id" INTEGER not null,
  "actor_id" INTEGER,
  "actor_name" TEXT,
  "type" TEXT CHECK ("type" IN ('kudos', 'comment', 'follow', 'conquest', 'conquest_attack', 'conquest_defend', 'conquest_win', 'achievement', 'challenge', 'record')),
  "body" TEXT,
  "link" TEXT,
  "read" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_user_notifications" ("id", "recipient_id", "actor_id", "actor_name", "type", "body", "link", "read", "created_at", "updated_at", "uuid") SELECT "id", "recipient_id", "actor_id", "actor_name", "type", "body", "link", "read", "created_at", "updated_at", "uuid" FROM "user_notifications";
DROP TABLE "user_notifications";
ALTER TABLE "_qb_tmp_user_notifications" RENAME TO "user_notifications";
CREATE UNIQUE INDEX IF NOT EXISTS "user_notifications_uuid_unique" ON "user_notifications" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
