-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE UNIQUE INDEX IF NOT EXISTS "saved_trails_user_trail_unique" ON "saved_trails" ("user_id", "trail_id");
CREATE UNIQUE INDEX IF NOT EXISTS "saved_trails_uuid_unique" ON "saved_trails" ("uuid");
