-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "user_privacy_settings" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "user_id" INTEGER not null REFERENCES "users"("id"),
  "default_activity_visibility" TEXT CHECK ("default_activity_visibility" IN ('public', 'followers', 'private')) not null DEFAULT 'followers',
  "hide_start_end_meters" INTEGER not null DEFAULT 400,
  "home_lat" REAL,
  "home_lng" REAL,
  "home_radius_meters" INTEGER not null DEFAULT 500,
  "exclude_home_from_game" INTEGER not null DEFAULT 1,
  "show_precise_territories" INTEGER not null DEFAULT 0,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
