-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "content_reports" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "reporter_id" INTEGER not null REFERENCES "users"("id") ON DELETE CASCADE,
  "subject_type" TEXT CHECK ("subject_type" IN ('user', 'activity', 'comment', 'trail_review', 'territory')) not null,
  "subject_id" INTEGER not null,
  "reason" TEXT CHECK ("reason" IN ('harassment', 'spam', 'unsafe', 'cheating', 'privacy', 'other')) not null,
  "details" TEXT,
  "status" TEXT CHECK ("status" IN ('open', 'reviewing', 'resolved', 'dismissed')) not null,
  "resolved_by" INTEGER REFERENCES "users"("id") ON DELETE SET NULL,
  "resolution_notes" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
