-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE UNIQUE INDEX IF NOT EXISTS "trail_ingest_shards_key_unique" ON "trail_ingest_shards" ("shard_key");
CREATE INDEX IF NOT EXISTS "trail_ingest_shards_source_status_index" ON "trail_ingest_shards" ("source", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "trail_ingest_shards_uuid_unique" ON "trail_ingest_shards" ("uuid");
