-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "activities" ADD COLUMN "anomaly_score" REAL default 0;
ALTER TABLE "activities" ADD COLUMN "integrity_flags" TEXT;
ALTER TABLE "activities" ADD COLUMN "track_fingerprint" TEXT;
ALTER TABLE "activities" ADD COLUMN "review_state" TEXT CHECK ("review_state" IN ('none', 'pending', 'cleared', 'upheld')) not null default 'none';
