-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "user_blocks" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "blocker_id" INTEGER not null REFERENCES "users"("id") ON DELETE CASCADE,
  "blocked_id" INTEGER not null REFERENCES "users"("id") ON DELETE CASCADE,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
