CREATE TABLE IF NOT EXISTS "territories" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "user_id" INTEGER REFERENCES "users"("id"),
  "activity_id" INTEGER REFERENCES "activities"("id"),
  "parent_territory_id" INTEGER,
  "name" TEXT,
  "polygon_data" TEXT,
  "bounding_box" TEXT,
  "center_lat" INTEGER,
  "center_lng" INTEGER,
  "area_size" INTEGER,
  "perimeter" INTEGER,
  "status" TEXT CHECK ("status" IN ('active', 'contested', 'expired')),
  "conquest_count" INTEGER,
  "claimed_at" TEXT,
  "last_activity_at" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);