-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "custom_routes" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "user_id" INTEGER not null REFERENCES "users"("id"),
  "name" TEXT not null,
  "route_data" TEXT not null,
  "distance" REAL,
  "elevation" REAL,
  "closed_loop" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
