-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "clubs" ADD COLUMN "join_policy" TEXT CHECK ("join_policy" IN ('open', 'request', 'invite_only')) not null;
