import { LatLng } from '../geo/LatLng';
import { Layer } from './Layer';
import { Point } from '../geometry/Point';
export declare class DivOverlay extends Layer {
  _latlng?: LatLng;
  _source?: any;
  _content?: any;
  _container?: HTMLElement;
  _contentNode?: HTMLElement;
  _removeTimeout?: ReturnType<typeof setTimeout>;
  _containerWidth?: number;
  _containerHeight?: number;
  _containerLeft?: number;
  _containerBottom?: number;
  _autopanning?: boolean;
  initialize(options?: any, source?: any): void;
  openOn(map?: any): this;
  close(): this;
  toggle(layer?: any): this;
  onAdd(map: any): void;
  onRemove(map: any): void;
  getLatLng(): LatLng | undefined;
  setLatLng(latlng: any): this;
  getContent(): any;
  setContent(content: any): this;
  getElement(): HTMLElement | undefined;
  update(): void;
  getEvents(): Record<string, any>;
  isOpen(): boolean;
  bringToFront(): this;
  bringToBack(): this;
  _prepareOpen(latlng?: LatLng): boolean;
  _updateContent(): void;
  _updatePosition(): void;
  _getAnchor(): Point | number[];
  _initLayout(): void;
  _updateLayout(): void;
  _adjustPan(): void;
  _animateZoom(_e: any): void;
}
