// GlyphAtlas — rasterises font glyphs to a single backing canvas and packs
// them via a simple shelf-packer. Each glyph gets an approximate signed
// distance field generated by a cheap 2-pass Chamfer 3-4 scan so callers can
// resample the atlas at any target size with tolerably smooth edges.
//
// Zero runtime deps. Designed to live alongside Canvas2D rendering today and
// graduate to WebGL sampling later without changing the public API.
export declare interface GlyphMetrics {
  codePoint: number
  x: number
  y: number
  width: number
  height: number
  advance: number
  bearingX: number
  bearingY: number
}
export declare interface GlyphAtlasOptions {
  fontFamily?: string
  fontSize?: number
  padding?: number
  bucketSize?: number
}
export declare class GlyphAtlas {
  canvas: HTMLCanvasElement;
  constructor(opts?: GlyphAtlasOptions);
  getOrAddGlyph(codePoint: number, style?: { italic?: boolean, bold?: boolean }): GlyphMetrics;
  measure(text: string, style?: { italic?: boolean, bold?: boolean, family?: string }): { width: number, height: number };
  advances(text: string, size: number, style?: { italic?: boolean, bold?: boolean, family?: string }): Array<{ char: string, advance: number }>;
  measureText(text: string, size: number, style?: { italic?: boolean, bold?: boolean, family?: string }): { width: number, height: number, ascent: number, descent: number };
  fontString(size: number, style?: { italic?: boolean, bold?: boolean, family?: string }): string;
  resolveFont(textFont: string | string[] | undefined): { family: string, bold: boolean, italic: boolean };
  drawText(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, options: {
      color: string
      haloColor?: string
      haloWidth?: number
      size: number
      italic?: boolean
      bold?: boolean
      family?: string
    }): void;
  _buildSDF(imageData: ImageData): ImageData;
}
